{ Application Version Information File                                 }
{                                                                      }
{ This file is created automatically by the version.sh script whenever }
{ the project is built by Lazarus. Manual changes will be lost.        }

const
  { The default Free Pascal Compiler }
  FPC_VERSION='3.2.2';
  FPC_PLATFORM='darwin';
  FPC_TARGET='x86_64';

  { The Lazarus I.D.E }
  LAZARUS_VERSION='4.0';

  { Source & Subversion Last Changed Commit }
  SOURCE_VERSION='0.0.0';
  SOURCE_REVISION='11';
  SOURCE_URL='http://github.com/shidel/utf8tools';
  SOURCE_COMMIT='55c3f82287744da3e4e441616c9ad2d6ee02f6db';

  { Version Build Atributes } 
  BUILD_DEBUG=False;
  BUILD_PRERELEASE=True;
  BUILD_PATCHED=False;
  BUILD_PRIVATE=False;
  BUILD_SPECIAL=False;
  BUILD_DATE='2025-07-11 04:04:31';

  { General Application Information }
  APP_IDENTIFIER='';
  APP_VERSION='0.0.0';
  APP_BUILD='0';
  APP_YEAR='2025';

