{ Application Version Information File                                 }
{                                                                      }
{ This file is created automatically by the version.sh script whenever }
{ the project is built by Lazarus. Manual changes will be lost.        }

const
  { The default Free Pascal Compiler }
  FPC_VERSION='3.2.2';
  FPC_PLATFORM='darwin';
  FPC_TARGET='x86_64';

  { The Lazarus I.D.E }
  LAZARUS_VERSION='4.0';

  { Source & Subversion Last Changed Commit }
  SOURCE_VERSION='0.0.0';
  SOURCE_REVISION='19';
  SOURCE_URL='http://github.com/shidel/utf8tools';
  SOURCE_COMMIT='7f154ef0a5e51804f613b87421f8b5ced55a0f15';

  { Version Build Atributes } 
  BUILD_DEBUG=False;
  BUILD_PRERELEASE=True;
  BUILD_PATCHED=False;
  BUILD_PRIVATE=False;
  BUILD_SPECIAL=False;
  BUILD_DATE='2025-07-13 07:01:00';

  { General Application Information }
  APP_IDENTIFIER='com.jeromeshidel.utf8converter';
  APP_VERSION='0.0.0';
  APP_BUILD='0';
  APP_COMMENTS='BSD-3-Clause license';
  APP_COMPANYNAME='Jerome Shidel';
  APP_FILEDESCRIPTION='UTF-8, HTML Entity and DOS code page converter';
  APP_INTERNALNAME='utf8converter';
  APP_LEGALCOPYRIGHT='2025 (c) Jerome Shidel';
  APP_ORIGINALFILENAME='utf8cnv';
  APP_PRODUCTNAME='UTF-8 Converter';
  APP_PRODUCTVERSION='1.0';
  APP_YEAR='2025';

